metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: jnlp
    env:
    - name: CONTAINER_ENV_VAR
      value: jnlp
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    command:
    - cat
    tty: true
    env:
    - name: CONTAINER_ENV_VAR
      value: maven
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
    env:
    - name: CONTAINER_ENV_VAR
      value: busybox
  - name: buildah
              image: quay.io/buildah/stable:v1.9.0
              tty: true
              command: ["/bin/bash"]
              workingDir: /home/jenkins/agent
              env: 
                - name: HOME
                  value: /home/devops
                - name: DOCKERFILE
                  value: ./Dockerfile
                - name: CONTEXT
                  value: .
                - name: TLSVERIFY
                  value: "false"
              volumeMounts:
                - mountPath: /var/lib/containers
                  name: varlibcontainers
