metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: jnlp
    env:
    - name: CONTAINER_ENV_VAR
      value: jnlp
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    command:
    - cat
    tty: true
    env:
    - name: CONTAINER_ENV_VAR
      value: maven
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
    env:
    - name: CONTAINER_ENV_VAR
      value: busybox
    - name: buildah
              image: quay.io/buildah/stable:v1.9.0
              tty: true
              command: ["/bin/bash"]
              workingDir: /home/jenkins/agent
              envFrom:
                - configMapRef:
                    name: ibmcloud-config
                    optional: true
                - secretRef:
                    name: ibmcloud-apikey
                    optional: true
              env: 
                - name: HOME
                  value: /home/devops
                - name: DOCKERFILE
                  value: ./Dockerfile
                - name: CONTEXT
                  value: .
                - name: TLSVERIFY
                  value: "false"
                - name: REGISTRY_USER
                  valueFrom:
                    secretKeyRef:
                      key: REGISTRY_USER
                      name: ibmcloud-apikey
                      optional: true
                - name: REGISTRY_PASSWORD
                 valueFrom:
                    secretKeyRef:
                      key: REGISTRY_PASSWORD
                      name: ibmcloud-apikey
                      optional: true
                - name: APIKEY
                  valueFrom:
                    secretKeyRef:
                      key: APIKEY
                      name: ibmcloud-apikey
                      optional: true
              volumeMounts:
                - mountPath: /var/lib/containers
                  name: varlibcontainers
